model_list:
  - model_name: openrouter/gpt-oss-20b
    litellm_params:
      model: openrouter/openrouter/gpt-oss-20b:free
      api_base: !ENV ${OPENROUTER_API_BASEURL}
      api_key: !ENV ${OPENROUTER_API_KEY}
  - model_name: google/gemma-3n-e2b-it
    litellm_params:
      model: openrouter/google/gemma-3n-e2b-it:free
      api_base: !ENV ${OPENROUTER_API_BASEURL}
      api_key: !ENV ${OPENROUTER_API_KEY}
  - model_name: Llama-3.1-70B
    litellm_params:
      model: openrouter/Llama-3.1-70B
      api_base: !ENV ${NCHC_API_BASEURL}
      api_key: !ENV ${NCHC_API_KEY}
  - model_name: Llama3-TAIDE-LX-8B-Chat-Alpha1
    litellm_params:
      model: openrouter/Llama3-TAIDE-LX-8B-Chat-Alpha1
      api_base: !ENV ${NCHC_API_BASEURL}
      api_key: !ENV ${NCHC_API_KEY}
  - model_name: Microsoft-Phi-4-multimodal-instruct
    litellm_params:
      model: openrouter/Microsoft-Phi-4-multimodal-instruct
      api_base: !ENV ${NCHC_API_BASEURL}
      api_key: !ENV ${NCHC_API_KEY}
  - model_name: Llama-3.3-70B-Instruct-Gaudi3
    litellm_params:
      model: openrouter/Llama-3.3-70B-Instruct-Gaudi3
      api_base: !ENV ${NCHC_API_BASEURL}
      api_key: !ENV ${NCHC_API_KEY}
  - model_name: Google-Gemma-3-27B
    litellm_params:
      model: openrouter/Google-Gemma-3-27B
      api_base: !ENV ${NCHC_API_BASEURL}
      api_key: !ENV ${NCHC_API_KEY}
  - model_name: Llama-3.3-70B-Instruct-MI210
    litellm_params:
      model: openrouter/Llama-3.3-70B-Instruct-MI210
      api_base: !ENV ${NCHC_API_BASEURL}
      api_key: !ENV ${NCHC_API_KEY}
  - model_name: Llama-3.1-Nemotron-70B-Instruct
    litellm_params:
      model: openrouter/Llama-3.1-Nemotron-70B-Instruct
      api_base: !ENV ${NCHC_API_BASEURL}
      api_key: !ENV ${NCHC_API_KEY}
  - model_name: Llama-3.1-TAIDE-LX-8B-Chat
    litellm_params:
      model: openrouter/Llama-3.1-TAIDE-LX-8B-Chat
      api_base: !ENV ${NCHC_API_BASEURL}
      api_key: !ENV ${NCHC_API_KEY}
  - model_name: Llama-4-Scout-17B-16E-Instruct-FP8
    litellm_params:
      model: openrouter/Llama-4-Scout-17B-16E-Instruct-FP8
      api_base: !ENV ${NCHC_API_BASEURL}
      api_key: !ENV ${NCHC_API_KEY}
  - model_name: Llama-3.2-90B-Vision-Instruct
    litellm_params:
      model: openrouter/Llama-3.2-90B-Vision-Instruct
      api_base: !ENV ${NCHC_API_BASEURL}
      api_key: !ENV ${NCHC_API_KEY}
  - model_name: Llama-3.1-8B-Instruct
    litellm_params:
      model: openrouter/Llama-3.1-8B-Instruct
      api_base: !ENV ${NCHC_API_BASEURL}
      api_key: !ENV ${NCHC_API_KEY}
  - model_name: Gemma-3-TAIDE-12b-Chat
    litellm_params:
      model: openrouter/Gemma-3-TAIDE-12b-Chat
      api_base: !ENV ${NCHC_API_BASEURL}
      api_key: !ENV ${NCHC_API_KEY}
  - model_name: gpt-oss-120b
    litellm_params:
      model: openrouter/gpt-oss-120b
      api_base: !ENV ${NCHC_API_BASEURL}
      api_key: !ENV ${NCHC_API_KEY}
  - model_name: Llama-4-Maverick-17B-128E-Instruct-FP8
    litellm_params:
      model: openrouter/Llama-4-Maverick-17B-128E-Instruct-FP8
      api_base: !ENV ${NCHC_API_BASEURL}
      api_key: !ENV ${NCHC_API_KEY}
  - model_name: Mistral-Small-3.1-24B-Instruct-2503
    litellm_params:
      model: openrouter/Mistral-Small-3.1-24B-Instruct-2503
      api_base: !ENV ${NCHC_API_BASEURL}
      api_key: !ENV ${NCHC_API_KEY}
  - model_name: Microsoft-Phi-4
    litellm_params:
      model: openrouter/Microsoft-Phi-4
      api_base: !ENV ${NCHC_API_BASEURL}
      api_key: !ENV ${NCHC_API_KEY}
  - model_name: Llama-3.1-Nemotron-70B-Instruct-Gaudi3
    litellm_params:
      model: openrouter/Llama-3.1-Nemotron-70B-Instruct-Gaudi3
      api_base: !ENV ${NCHC_API_BASEURL}
      api_key: !ENV ${NCHC_API_KEY}
  - model_name: Llama-3.1-405B-Instruct-FP8
    litellm_params:
      model: openrouter/Llama-3.1-405B-Instruct-FP8
      api_base: !ENV ${NCHC_API_BASEURL}
      api_key: !ENV ${NCHC_API_KEY}
  - model_name: medgemma-27b-it
    litellm_params:
      model: openrouter/medgemma-27b-it
      api_base: !ENV ${NCHC_API_BASEURL}
      api_key: !ENV ${NCHC_API_KEY}
  - model_name: gpt-oss-20b
    litellm_params:
      model: openrouter/gpt-oss-20b
      api_base: !ENV ${NCHC_API_BASEURL}
      api_key: !ENV ${NCHC_API_KEY}
  - model_name: Llama-3.3-70B-Instruct
    litellm_params:
      model: openrouter/Llama-3.3-70B-Instruct
      api_base: !ENV ${NCHC_API_BASEURL}
      api_key: !ENV ${NCHC_API_KEY}
  - model_name: Mistral-Small-24B-Instruct-2501
    litellm_params:
      model: openrouter/Mistral-Small-24B-Instruct-2501
      api_base: !ENV ${NCHC_API_BASEURL}
      api_key: !ENV ${NCHC_API_KEY}
  - model_name: Multilingual-E5-Large-Instruct
    litellm_params:
      model: openrouter/Multilingual-E5-Large-Instruct
      api_base: !ENV ${NCHC_API_BASEURL}
      api_key: !ENV ${NCHC_API_KEY}
  - model_name: TAIDE-LX-7B-Chat
    litellm_params:
      model: openrouter/TAIDE-LX-7B-Chat
      api_base: !ENV ${NCHC_API_BASEURL}
      api_key: !ENV ${NCHC_API_KEY}
  - model_name: Llama-3.3-Nemotron-Super-49B-v1
    litellm_params:
      model: openrouter/Llama-3.3-Nemotron-Super-49B-v1
      api_base: !ENV ${NCHC_API_BASEURL}
      api_key: !ENV ${NCHC_API_KEY}
  - model_name: Ministral-8B-Instruct-2410
    litellm_params:
      model: openrouter/Ministral-8B-Instruct-2410
      api_base: !ENV ${NCHC_API_BASEURL}
      api_key: !ENV ${NCHC_API_KEY}
dataset_path: !ENV ${PWD}/datasets

